# Generated by Django 4.2.19 on 2025-03-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': False, 'ordering': ['ischecked', 'name']},
        ),
    ]
